### ISSUE TITLE
Gracefully Handle Failed Query Execution

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/dune-sync#11]
[This query](https://dune.com/queries/4063502/6842185) `4063502` (one from the dashboard) is failing query execution...

and we are getting the following error log:

```
2024-10-13 15:57:19,344 INFO dune_client.api.base waiting for query execution 01JA32869BDVFB684NGX6HW5PG to complete: ExecutionState.EXECUTING
2024-10-13 15:57:29,432 INFO dune_client.api.base waiting for query execution 01JA32869BDVFB684NGX6HW5PG to complete: ExecutionState.EXECUTING
2024-10-13 15:57:39,508 ERROR dune_client.api.base ExecutionState.FAILED: execution_id=01JA32869BDVFB684NGX6HW5PG, query_id=4063502, times=TimeData(submitted_at=datetime.datetime(2024, 10, 13, 13, 49, 25, 676335, tzinfo=tzutc()), execution_started_at=datetime.datetime(2024, 10, 13, 13, 56, 31, 318547, tzinfo=tzutc()), execution_ended_at=datetime.datetime(2024, 10, 13, 13, 57, 35, 16998, tzinfo=tzutc()), expires_at=datetime.datetime(2025, 1, 11, 13, 57, 35, 16998, tzinfo=tzutc()), cancelled_at=None)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/bh2smith/Projects/bh2smith/dune-sync/src/main.py", line 60, in <module>
    main()
  File "/Users/bh2smith/Projects/bh2smith/dune-sync/src/main.py", line 54, in main
    df, types = fetch_dune_data()
                ^^^^^^^^^^^^^^^^^
  File "/Users/bh2smith/Projects/bh2smith/dune-sync/src/main.py", line 30, in fetch_dune_data
    .run_query(query=QueryBase(QUERY_ID), ping_frequency=POLL_FREQUENCY)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bh2smith/Projects/bh2smith/dune-sync/.venv/lib/python3.12/site-packages/dune_client/api/extensions.py", line 78, in run_query
    job_id = self._refresh(query, ping_frequency, performance)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bh2smith/Projects/bh2smith/dune-sync/.venv/lib/python3.12/site-packages/dune_client/api/extensions.py", line 425, in _refresh
    raise QueryFailed(f"Error data: {status.error}")
dune_client.models.QueryFailed: Error data: None
```

Related to #6 (ish)

**Comment by bh2smith** [comment]
Won't fix. The trace on the error is good enough.
