### ISSUE TITLE
docker run results in unexpected error

### ISSUE THREAD

**Issue by fleupold** [bh2smith/dune-sync#74]
Running the command

```
docker run ghcr.io/bh2smith/dune-sync:latest
```

results in the following output:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/src/main.py", line 26, in <module>
    from src.config import RuntimeConfig
  File "/app/src/config.py", line 13, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by bh2smith** [comment]
I think we need to add this to the requirements. Good catch.
